modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
[[mods]]
modId = "tinkersdisassembler"
version = "1.0.0"
displayName = "Tinkers Disassembler"
displayURL = "f1cont.com"
authors = "niki119"
description = '''
Disassemble your tools
'''
[[dependencies.tinkersdisassembler]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tinkersdisassembler]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tinkersdisassembler]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.3.4,)"
ordering = "NONE"
side = "BOTH"